export interface CatalogItem {
  id: string;
  name: string;
  category: string;
  width: number;   // meters (X)
  depth: number;   // meters (Z)
  height: number;  // meters (Y)
  color: string;
  clearance: number;
  description: string;
  icon: string;
}

export const CATEGORIES = [
  { id: 'shelving', name: 'Rafturi & Gondole', icon: '🗄️' },
  { id: 'counters', name: 'Case & Tejghele', icon: '🏪' },
  { id: 'refrigeration', name: 'Frigidere & Vitrine', icon: '❄️' },
  { id: 'food', name: 'Food & Cafea', icon: '☕' },
  { id: 'furniture', name: 'Mobilier', icon: '🪑' },
  { id: 'tech', name: 'Echipamente', icon: '📺' },
  { id: 'safety', name: 'Siguranță', icon: '🔥' },
] as const;

export const CATALOG: CatalogItem[] = [
  // ===== RAFTURI & GONDOLE =====
  {
    id: 'gondola-double-90',
    name: 'Gondolă Dublă 90cm',
    category: 'shelving',
    width: 0.90, depth: 0.92, height: 1.37,
    color: '#A0A0A0', clearance: 0.9,
    description: 'Gondolă centrală dublă, 4 polițe/față',
    icon: '🗄️',
  },
  {
    id: 'gondola-double-60',
    name: 'Gondolă Dublă 60cm',
    category: 'shelving',
    width: 0.60, depth: 0.92, height: 1.37,
    color: '#A0A0A0', clearance: 0.9,
    description: 'Gondolă centrală scurtă',
    icon: '🗄️',
  },
  {
    id: 'endcap-display',
    name: 'Cap Gondolă',
    category: 'shelving',
    width: 0.90, depth: 0.55, height: 1.37,
    color: '#B8860B', clearance: 0.8,
    description: 'Display cap gondolă promoții',
    icon: '🗄️',
  },
  {
    id: 'shelf-wall-90',
    name: 'Raft Perete 90cm',
    category: 'shelving',
    width: 0.90, depth: 0.45, height: 2.0,
    color: '#8B8682', clearance: 0.8,
    description: 'Raft de perete, 5 polițe',
    icon: '🗄️',
  },
  {
    id: 'shelf-wall-90-tall',
    name: 'Raft Perete Înalt 90cm',
    category: 'shelving',
    width: 0.90, depth: 0.45, height: 2.20,
    color: '#8B8682', clearance: 0.8,
    description: 'Raft de perete înalt, 6 polițe (auto/accesorii)',
    icon: '🗄️',
  },
  {
    id: 'magazine-rack',
    name: 'Stand Reviste',
    category: 'shelving',
    width: 0.90, depth: 0.35, height: 1.50,
    color: '#696969', clearance: 0.6,
    description: 'Stand reviste/ziare de perete',
    icon: '📰',
  },

  // ===== CASE & TEJGHELE =====
  {
    id: 'counter-main',
    name: 'Tejghea Casă Principală',
    category: 'counters',
    width: 2.40, depth: 0.80, height: 0.90,
    color: '#5C4033', clearance: 1.2,
    description: 'Tejghea principală cu POS, scanner, terminal card',
    icon: '🏪',
  },
  {
    id: 'counter-secondary',
    name: 'Tejghea Secundară',
    category: 'counters',
    width: 1.50, depth: 0.70, height: 0.90,
    color: '#5C4033', clearance: 1.0,
    description: 'Tejghea secundară/info',
    icon: '🏪',
  },
  {
    id: 'tobacco-display',
    name: 'Vitrină Tutun',
    category: 'counters',
    width: 2.00, depth: 0.35, height: 1.25,
    color: '#696969', clearance: 0.6,
    description: 'Vitrină tutun perete, 6 polițe cu pushers',
    icon: '🚬',
  },
  {
    id: 'impulse-rack',
    name: 'Rack Impuls Casă',
    category: 'counters',
    width: 0.40, depth: 0.25, height: 0.90,
    color: '#CD853F', clearance: 0.3,
    description: 'Rack gumă/bomboane lateral casă',
    icon: '🍬',
  },
  {
    id: 'impulse-undertejghea',
    name: 'Display Sub-Tejghea',
    category: 'counters',
    width: 0.85, depth: 0.25, height: 0.80,
    color: '#CD853F', clearance: 0.3,
    description: 'Wire rack 4 polițe, integrat în tejghea',
    icon: '🍬',
  },

  // ===== FRIGIDERE & VITRINE =====
  {
    id: 'fridge-1door',
    name: 'Frigider 1 Ușă',
    category: 'refrigeration',
    width: 0.56, depth: 0.65, height: 2.0,
    color: '#E8E8E8', clearance: 0.1,
    description: 'Frigider vertical 1 ușă sticlă, 310L',
    icon: '❄️',
  },
  {
    id: 'fridge-2door',
    name: 'Frigider 2 Uși',
    category: 'refrigeration',
    width: 1.00, depth: 0.68, height: 2.0,
    color: '#E8E8E8', clearance: 0.1,
    description: 'Frigider vertical 2 uși sticlă, 650L',
    icon: '❄️',
  },
  {
    id: 'fridge-3door',
    name: 'Frigider 3 Uși',
    category: 'refrigeration',
    width: 1.50, depth: 0.68, height: 2.0,
    color: '#E8E8E8', clearance: 0.1,
    description: 'Frigider 3 uși sticlă, 1000L (standard VIVA)',
    icon: '❄️',
  },
  {
    id: 'fridge-wall-6door',
    name: 'Perete Frigidere 6 Uși',
    category: 'refrigeration',
    width: 3.50, depth: 0.68, height: 2.0,
    color: '#D0D0D0', clearance: 0.1,
    description: 'Modul perete complet băuturi, 6 uși sticlă',
    icon: '❄️',
  },
  {
    id: 'freezer-chest',
    name: 'Ladă Frigorifică',
    category: 'refrigeration',
    width: 1.30, depth: 0.65, height: 0.90,
    color: '#F0F0F0', clearance: 0.8,
    description: 'Ladă frigorifică 300-400L, capac sticlă glisant',
    icon: '❄️',
  },
  {
    id: 'ice-cream-freezer',
    name: 'Congelator Înghețată',
    category: 'refrigeration',
    width: 1.00, depth: 0.60, height: 0.85,
    color: '#FAFAFA', clearance: 0.8,
    description: 'Congelator înghețată, capac curbat sticlă',
    icon: '🍦',
  },
  {
    id: 'sandwich-display',
    name: 'Vitrină Sandvișuri',
    category: 'refrigeration',
    width: 0.90, depth: 0.55, height: 0.40,
    color: '#C0C0C0', clearance: 0.5,
    description: 'Vitrină refrigerată sandvișuri countertop',
    icon: '🥪',
  },
  {
    id: 'grab-and-go',
    name: 'Vitrină Grab & Go',
    category: 'refrigeration',
    width: 0.70, depth: 0.65, height: 1.40,
    color: '#D0D0D0', clearance: 0.6,
    description: 'Vitrină refrigerată verticală salate/sucuri fresh',
    icon: '🥗',
  },
  {
    id: 'pastry-display',
    name: 'Vitrină Patiserie',
    category: 'refrigeration',
    width: 0.70, depth: 0.57, height: 0.68,
    color: '#E8D0B0', clearance: 0.5,
    description: 'Vitrină patiserie refrigerată, sticlă curbată',
    icon: '🥐',
  },
  {
    id: 'heated-display',
    name: 'Vitrină Caldă',
    category: 'refrigeration',
    width: 0.70, depth: 0.50, height: 0.65,
    color: '#FF8C00', clearance: 0.5,
    description: 'Vitrină caldă 3 nivele (VIVA Baciata/Pita)',
    icon: '🔥',
  },

  // ===== FOOD & CAFEA (VIVA) =====
  {
    id: 'coffee-machine-main',
    name: 'Automat Cafea VIVA',
    category: 'food',
    width: 0.43, depth: 0.56, height: 0.71,
    color: '#2C2C2C', clearance: 0.5,
    description: 'Schaerer Coffee Art Plus, 2 hoppers, touchscreen',
    icon: '☕',
  },
  {
    id: 'coffee-machine-secondary',
    name: 'Automat Cafea Secundar',
    category: 'food',
    width: 0.33, depth: 0.59, height: 0.68,
    color: '#2C2C2C', clearance: 0.5,
    description: 'WMF 1500 S+, 3 hoppers, touch 10"',
    icon: '☕',
  },
  {
    id: 'coffee-corner-table',
    name: 'Masă Coffee Corner',
    category: 'food',
    width: 1.20, depth: 0.60, height: 0.90,
    color: '#5C4033', clearance: 0.6,
    description: 'Blat condimente (zahăr, scorțișoară, agitator)',
    icon: '☕',
  },
  {
    id: 'coffee-fridge',
    name: 'Frigider Lapte Sub-Tejghea',
    category: 'food',
    width: 0.25, depth: 0.50, height: 0.45,
    color: '#C0C0C0', clearance: 0.2,
    description: 'Frigider lapte conectat la automat cafea',
    icon: '🥛',
  },
  {
    id: 'microwave-station',
    name: 'Stație Microunde',
    category: 'food',
    width: 0.60, depth: 0.50, height: 0.90,
    color: '#3C3C3C', clearance: 0.6,
    description: 'Suport + cuptor microunde comercial 1000W',
    icon: '📡',
  },
  {
    id: 'hot-dog-grill',
    name: 'Roller Grill Hot Dog',
    category: 'food',
    width: 0.60, depth: 0.40, height: 0.30,
    color: '#CD853F', clearance: 0.5,
    description: 'Roller grill 20-30 crenvurști, capac sticlă',
    icon: '🌭',
  },
  {
    id: 'slush-machine',
    name: 'Mașină Slush',
    category: 'food',
    width: 0.40, depth: 0.53, height: 0.84,
    color: '#00CED1', clearance: 0.5,
    description: 'Slush/frozen drink 2 cuve x 10L, iluminat',
    icon: '🧊',
  },
  {
    id: 'juice-machine',
    name: 'Storcător Fresh',
    category: 'food',
    width: 0.50, depth: 0.55, height: 0.80,
    color: '#FF8C00', clearance: 0.5,
    description: 'Storcător portocale automat (VIVA Fresh Juices)',
    icon: '🍊',
  },

  // ===== UȘI =====
  {
    id: 'door-auto-double',
    name: 'Ușă Automată Dublă',
    category: 'furniture',
    width: 2.00, depth: 0.12, height: 2.30,
    color: '#88bbdd', clearance: 1.5,
    description: 'Ușă automată dublă sticlă, tip benzinărie, cu senzor',
    icon: '🚪',
  },
  {
    id: 'door-80',
    name: 'Ușă 80cm',
    category: 'furniture',
    width: 0.80, depth: 0.04, height: 2.10,
    color: '#8B6914', clearance: 0.9,
    description: 'Ușă interioară 80cm cu toc',
    icon: '🚪',
  },
  {
    id: 'door-90',
    name: 'Ușă 90cm',
    category: 'furniture',
    width: 0.90, depth: 0.04, height: 2.10,
    color: '#8B6914', clearance: 0.9,
    description: 'Ușă interioară 90cm cu toc',
    icon: '🚪',
  },
  {
    id: 'door-100',
    name: 'Ușă 100cm',
    category: 'furniture',
    width: 1.00, depth: 0.04, height: 2.10,
    color: '#8B6914', clearance: 1.0,
    description: 'Ușă interioară 100cm cu toc',
    icon: '🚪',
  },

  // ===== MOBILIER =====
  {
    id: 'bar-table-long',
    name: 'Masă Bar Lungă',
    category: 'furniture',
    width: 1.20, depth: 0.50, height: 1.10,
    color: '#8B7355', clearance: 0.6,
    description: 'Masă înaltă bar la geam, blat laminat',
    icon: '🪑',
  },
  {
    id: 'bar-table-round',
    name: 'Masă Bar Rotundă',
    category: 'furniture',
    width: 0.60, depth: 0.60, height: 1.10,
    color: '#8B7355', clearance: 0.6,
    description: 'Masă înaltă rotundă Ø60cm',
    icon: '🪑',
  },
  {
    id: 'bar-stool',
    name: 'Scaun Bar',
    category: 'furniture',
    width: 0.40, depth: 0.40, height: 1.00,
    color: '#696969', clearance: 0.3,
    description: 'Scaun bar metalic/plastic, h=75cm',
    icon: '🪑',
  },
  {
    id: 'bench-wall',
    name: 'Banchetă Perete',
    category: 'furniture',
    width: 1.20, depth: 0.50, height: 0.90,
    color: '#8B4513', clearance: 0.6,
    description: 'Banchetă fixă tapițată, zonă mâncat',
    icon: '🛋️',
  },
  {
    id: 'trash-selective',
    name: 'Coș Gunoi Selectiv',
    category: 'furniture',
    width: 0.90, depth: 0.40, height: 0.90,
    color: '#4A4A4A', clearance: 0.3,
    description: '3 compartimente: hârtie/plastic/rezidual',
    icon: '♻️',
  },
  {
    id: 'trash-small',
    name: 'Coș Gunoi Mic',
    category: 'furniture',
    width: 0.30, depth: 0.30, height: 0.60,
    color: '#4A4A4A', clearance: 0.2,
    description: 'Coș push-top inox, la masă',
    icon: '🗑️',
  },

  // ===== ECHIPAMENTE TEHNICE =====
  {
    id: 'atm',
    name: 'Bancomat ATM',
    category: 'tech',
    width: 0.45, depth: 0.60, height: 1.45,
    color: '#1E90FF', clearance: 1.0,
    description: 'Bancomat freestanding BCR/BRD/ING',
    icon: '💳',
  },
  {
    id: 'self-payment',
    name: 'Terminal Self-Service',
    category: 'tech',
    width: 0.50, depth: 0.45, height: 1.40,
    color: '#4A4A4A', clearance: 0.8,
    description: 'Terminal plată carburant, touchscreen + NFC',
    icon: '💳',
  },
  {
    id: 'promo-totem',
    name: 'Totem Promoții',
    category: 'tech',
    width: 0.60, depth: 0.40, height: 1.70,
    color: '#333333', clearance: 0.5,
    description: 'Totem floor-standing cu LCD 43"',
    icon: '📺',
  },
  {
    id: 'lcd-wall-43',
    name: 'Monitor LCD 43"',
    category: 'tech',
    width: 0.97, depth: 0.08, height: 0.57,
    color: '#1a1a1a', clearance: 0.0,
    description: 'Monitor perete, digital signage promoții VIVA',
    icon: '📺',
  },
  {
    id: 'lcd-wall-32',
    name: 'Monitor LCD 32"',
    category: 'tech',
    width: 0.73, depth: 0.07, height: 0.44,
    color: '#1a1a1a', clearance: 0.0,
    description: 'Monitor deasupra casei, meniu/promoții',
    icon: '📺',
  },

  // ===== SIGURANȚĂ =====
  {
    id: 'fire-extinguisher',
    name: 'Stingător 6kg',
    category: 'safety',
    width: 0.16, depth: 0.16, height: 0.52,
    color: '#FF0000', clearance: 0.5,
    description: 'Stingător ABC 6kg + suport perete',
    icon: '🧯',
  },
  {
    id: 'first-aid',
    name: 'Trusă Prim Ajutor',
    category: 'safety',
    width: 0.30, depth: 0.12, height: 0.22,
    color: '#FFFFFF', clearance: 0.3,
    description: 'Cutie ABS perete, conformă SSM',
    icon: '🏥',
  },
  {
    id: 'exit-sign',
    name: 'Iluminat Urgență EXIT',
    category: 'safety',
    width: 0.30, depth: 0.05, height: 0.15,
    color: '#00FF00', clearance: 0.0,
    description: 'Montaj deasupra ușilor',
    icon: '🚪',
  },
  {
    id: 'evacuation-plan',
    name: 'Plan Evacuare',
    category: 'safety',
    width: 0.40, depth: 0.01, height: 0.30,
    color: '#00AA00', clearance: 0.0,
    description: 'Panou plan evacuare, lângă intrare',
    icon: '🗺️',
  },
];

export function getCatalogByCategory(category: string): CatalogItem[] {
  return CATALOG.filter(item => item.category === category);
}
